name: games_free
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.3+7

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.2
  firebase_messaging: 11.2.15
  awesome_notifications: 0.0.6+12
  google_mobile_ads: ^1.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  package_info_plus: ^1.4.2
  cached_network_image: ^3.2.1
  get_it: ^7.2.0
  http: ^0.13.4
  firebase_core: ^1.17.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
    
flutter_native_splash:
  flutter_native_splash:
  image: assets/splash.png
  color: "ffffff"
  android_disable_fullscreen: false
  fill: false
  ios: false
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icone.png"
  # flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

